name: Discord Release Notification

on:
  release:
    types: [published]

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send release to Discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        run: |
          curl -H "Content-Type: application/json" \
          -d "$(cat <<EOF
          {
            "embeds": [
              {
                "title": "${{ github.event.release.name }}",
                "url": "${{ github.event.release.html_url }}",
                "description": "${{ github.event.release.body }}",
                "color": 5814783,
                "footer": {
                  "text": "SEPSIS Update"
                },
                "timestamp": "${{ github.event.release.published_at }}"
              }
            ]
          }
          EOF
          )" \
          "$DISCORD_WEBHOOK"
